package com.sampathgrocery.dto.product;

import com.sampathgrocery.entity.product.Product;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Product Request DTO
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ProductRequest {

    // Optional - auto-generated by backend if not provided
    @Size(max = 30)
    private String productCode;

    @NotBlank(message = "Product name is required")
    @Size(max = 200)
    private String productName;

    @NotNull(message = "Category is required")
    private Integer categoryId;

    private Integer brandId; // Optional - can be null

    @Size(max = 100)
    private String barcode;

    @NotNull(message = "Unit of measure is required")
    private Integer unitId;

    @Size(max = 1000)
    private String description;

    private String imageUrl;

    @Min(value = 0)
    private Integer reorderPoint = 10;

    @Min(value = 0)
    private Integer reorderQuantity = 50;

    private Boolean isActive = true;
}
