package com.sampathgrocery.dto.employee;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.sampathgrocery.dto.user.UserDTO;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * DTO for Employee entity
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class EmployeeDTO {

    @JsonProperty("employeeId")
    private Integer employeeId;

    @JsonProperty("employeeCode")
    private String employeeCode; // Auto-generated by backend

    @JsonProperty("user")
    private UserDTO user;

    @NotBlank(message = "Full name is required")
    @JsonProperty("fullName")
    private String fullName;

    @JsonProperty("nic")
    private String nic;

    @JsonProperty("dateOfBirth")
    private LocalDate dateOfBirth;

    @JsonProperty("gender")
    private String gender;

    @NotBlank(message = "Phone is required")
    @JsonProperty("phone")
    private String phone;

    @JsonProperty("alternatePhone")
    private String alternatePhone;

    @JsonProperty("email")
    private String email;

    @NotBlank(message = "Address is required")
    @JsonProperty("address")
    private String address;

    @JsonProperty("city")
    private String city;

    @NotBlank(message = "Designation is required")
    @JsonProperty("designation")
    private String designation;

    @JsonProperty("isActive")
    private Boolean isActive;

    @JsonProperty("createdAt")
    private LocalDateTime createdAt;

    @JsonProperty("updatedAt")
    private LocalDateTime updatedAt;
}
